-- Add migration script here
CREATE TABLE shows (
    id SERIAL PRIMARY KEY UNIQUE,
    show_date DATE NOT NULL,
    venue VARCHAR(255) NOT NULL,
    ticketing_link VARCHAR,
    artwork VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)
